# -*- coding: utf-8 -*-
"""longflow.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s8d3awvYw57ObMZCRXf1NiRpZhBiazJ8
"""

# Make sure to upload LongFlow.csv to the storage of this notebook!
import csv
import pandas as pd

# Read the CSV file into a pandas DataFrame, handling empty fields as ""
df = pd.read_csv("LongFlow.csv", na_values="")

datetime_format="%m/%d/%y %H:%M"

# Read network bytes and fill with 0 in cases where the connection has not stopped
df['network.bytes'] = pd.to_numeric(df['network.bytes'].fillna(0), errors='coerce')

# Read port numbers and convert to integers
df['source.port'] = pd.to_numeric(df['source.port'].fillna(0), errors='coerce')
df['source.port'] = df['source.port'].astype(int)
df['destination.port'] = pd.to_numeric(df['destination.port'].fillna(0), errors='coerce')
df['destination.port'] = df['destination.port'].astype(int)

# Convert timestamp columns to datetime format
df['end_timestamp'] = pd.to_datetime(df['end_timestamp'].fillna('11/27/19 8:00'), format=datetime_format, errors='coerce')
df['start_timestamp'] = pd.to_datetime(df['start_timestamp'].fillna('11/26/19 8:00'),format=datetime_format, errors='coerce')

# Calculate duration
df['duration'] = pd.to_timedelta(df['end_timestamp'] - df['start_timestamp'])/pd.Timedelta('60s')

# Group data by source IP and destination IP to analyze traffic patterns
grouped_data = df.groupby(['source.ip', 'destination.ip']).agg({'network.bytes': 'sum', 'duration': 'mean'})

# Print top of file and data types
print((df.head().to_markdown()))
print(df.dtypes.to_markdown())

# Print summary statistics of grouping
print(grouped_data.describe())

# Make an enum of common port numbers
expected_ports = {
  22: "SSH",
  80: "HTTP",
  443: "HTTPS",
  53: "DNS",
  # ... add more expected ports
}

# Filter out expected_ports to leave only unexpected_ports
unexpected_ports = df[~df["destination.port"].isin(expected_ports.keys())]["destination.port"].unique()

if len(unexpected_ports) > 0:
  print(f"Unexpected ports detected: {unexpected_ports}")

port_stats = df.groupby("destination.port").agg({"network.bytes": ["mean", "std"]})

threshold = 250
low_threshold = 25

# Find ports with unusual traffic patterns
anomalous_ports = port_stats[(port_stats["network.bytes"]["std"] > threshold) | (port_stats["network.bytes"]["mean"] < low_threshold)]

print("Anomalous ports based on traffic patterns:")
print(anomalous_ports.to_markdown())

